namespace SSMP.Game.Client.Entity;

/// <summary>
/// Enumeration of entity types. The entries more closely resemble the canonical name rather than the internal naming.
/// </summary>
internal enum EntityType {
    Mossgrub,
    MassiveMossgrub,
    Mossmir,
    MossMother,
    MossboneStalactite,
    Aknid,
    SkullScuttler,
    Skullwing,
    SkullBrute,
    SkullTyrant,
    Kilik,
    Beastfly,
    SavageBeastfly,
    Caranid,
    ViciousCaranid,
    HardboneHopper,
    HardboneElder,
    Tarmite,
    Mawling,
    Marrowmaw,
    Hoker,
    Flintbeetle,
    Rhinogrund,
    Gromling,
    Grom,
    BellBeast,
    PilgrimGroveller,
    PilgrimPouncer,
    PilgrimHornfly,
    PilgrimHulk,
    PilgrimBellbearer,
    WingedPilgrim,
    ElderPilgrim,
    WingedPilgrimBellbearer,
    PilgrimHiker,
    PilgrimGuide,
    OvergrownPilgrim,
    CovetousPilgrim,
    Snitchfly,
    Lavalug,
    Lavalarga,
    SmeltShoveller,
    FlintstoneFlyer,
    FlintflameFlyer,
    SmokerockSifter,
    DeepDiver,
    ForebrothersSignisAndGron,
    Cragglite,
    Craggler,
    Brushflit,
    Fertid,
    FlappingFertid,
    FourthChorus,
    Skarrlid,
    Skarrwing,
    SkarrScout,
    SkarrStalker,
    SpearSkarr,
    Skarrgard,
    GurrTheOutcast,
    LastClaw,
    SkarrsingerKarmelita,
    Mite,
    Fluttermite,
    Mitemother,
    DregCatcher,
    SilkSnipper,
    ThreadRaker,
    Moorwing,
    Wisp,
    BurningBug,
    FatherOfTheFlame,
    Craw,
    Tallcraw,
    Squatcraw,
    CrawJuror,
    TallcrawJuror,
    SquatcrawJuror,
    Crawfather,
    Muckmaggot,
    Slubberlug,
    Muckroach,
    Bloatroach,
    Roachcatcher,
    Roachfeeder,
    Roachkeeper,
    Roachserver,
    DisgracedChefLugoli,
    Wraith,
    MothleafLagnia,
    Miremite,
    SwampSquit,
    SpitSquit,
    Stilkin,
    StilkinTrapper,
    GroalTheGreat,
    Barnak,
    Ductsucker,
    PondSkipper,
    Pondcatcher,
    ShellwoodGnat,
    WoodWasp,
    Splinter,
    Splinterhorn,
    Splinterbark,
    SisterSplinter,
    Phacia,
    Pollenica,
    Gahlia,
    ShrineGuardianSeth,
    Nyleth,
    Furm,
    WingedFurm,
    Pharlid,
    PharlidDiver,
    Shardillard,
    Sandcarver,
    Squirrm,
    Judge,
    LastJudge,
    CoralFurm,
    Driznit,
    Driznarga,
    Pokenabbin,
    Conchfly,
    GreatConchfly,
    GreatConchflies,
    RagingConchfly,
    Crustcrawler,
    Crustcrag,
    Kai,
    SpinebeakKai,
    SteelspineKai,
    Yuma,
    Yumama,
    Karaka,
    Kakri,
    Yago,
    KarakGor,
    Alita,
    CorrcrustKaraka,
    CrustKingKhann,
    WatcherAtTheEdge,
    Voltvyrm,
    Drapefly,
    Drapelord,
    Drapemite,
    GiantDrapemite,
    Underworker,
    Underscrub,
    Undersweep,
    Underpoke,
    Underloft,
    Undercrank,
    Envoy,
    ChoirPouncer,
    ChoirHornhead,
    ChoirBellbearer,
    ChoirFlyer,
    ChoirElder,
    Choristor,
    Reed,
    GrandReed,
    ChoirClapper,
    Clawmaiden,
    Memoria,
    Minister,
    Maestro,
    SecondSentinel,
    DregHusk,
    Dregwheel,
    Surgeon,
    Mortician,
    TheUnravelled,
    CogworkUnderfly,
    CogworkHauler,
    CogworkCrawler,
    Cogworker,
    CogworkSpine,
    CogworkChoirbug,
    CogworkCleanser,
    CogworkDefender,
    CogworkClapper,
    CogworkDancers,
    Vaultborn,
    Lampbearer,
    Scrollreader,
    Vaultkeeper,
    Trobbio,
    TormentedTrobbio,
    Penitent,
    PunyPenitent,
    Freshfly,
    Scabfly,
    Guardfly,
    Wardenfly,
    Broodmother,
    Driftlin,
    Mnemonid,
    Mnemonord,
    ServitorIgnim,
    ServitorBoran,
    WingedLifeseed,
    Plasmid,
    Plasmidas,
    PlasmifiedZango,
    LeafGlider,
    LeafRoller,
    Pendra,
    Pendragor,
    Nuphar,
    Cloverstag,
    Palestag,
    Kindanir,
    Verdanir,
    Escalion,
    CloverDancers,
    ShadowCreeper,
    ShadowCharger,
    Gloomsac,
    GargantGloom,
    VoidTendrils,
    SummonedSaviour,
    Wingmould,
    Garpid,
    Imoba,
    Skrill,
    BellEater,
    HugeFlea,
    Shakra,
    GarmondAndZaza,
    LostGarmond,
    Pinstress,
    Widow,
    FirstSinner,
    Phantom,
    Lace,
    GrandMotherSilk,
    LostLace,
    GrassBall,
    BellfleaBouncer,
    BellfleaBouncerGiant,
    BellfleaJuggler,
    BellfleaJugglerGiant,
    BellfleaSwooper,
    BellfleaGameStart,
    SongAutomatonTiny,
    AspidHatchling,

    /// <summary>
    /// Not a creature: what a creature that the room makes itself is spawned by in a spawn message (see
    /// <see cref="RoomCreatures"/>). No registry entry has this type.
    /// </summary>
    Room,

    /// <summary>
    /// Not a creature: a rock of the room that a boss makes fall. Where it falls and how fast is rolled by the room,
    /// so each game rolled its own and the two games saw different rocks. Only the scene host's game runs them now.
    /// </summary>
    FourthChorusLavaRock,

    /// <summary>
    /// Not a creature: a cage that a boss drops, which lets a creature out where it lands. Where it drops and when is
    /// rolled by the cage, so each game dropped its own at a place of its own, while the creature it let out was the
    /// scene host's. Only the scene host's game runs them now, and the other game's copy falls by itself from where
    /// it set off (OwnMotionComponent).
    /// </summary>
    EnemySummonCage,

    /// <summary>
    /// Not a creature: a boulder hanging in a room that drops when a player comes near. It dropped in the game of the
    /// player who came near and nowhere else, so the other player neither saw it fall nor lost it. Only the scene
    /// host's game runs them now: a player coming near the other game's copy has it start there and tells the scene
    /// host (ListenForTouches), and the copy falls by itself, speeding up step by step (OwnMotionComponent).
    /// </summary>
    BoneBoulder,

    /// <summary>
    /// Not a creature: a boulder that a boss drops in its fight, which each game dropped with a look and a wait of its
    /// own. Only the scene host's game runs them now, and the copy falls by itself (OwnMotionComponent).
    /// </summary>
    BattleBoneBoulder,

    /// <summary>
    /// Not a creature: a bell that a boss drops, which bounces off the floor. Where it drops and which way it bounces
    /// was rolled by each game. Only the scene host's game runs them now, and the copy falls and bounces by itself
    /// with the same gravity (OwnMotionComponent).
    /// </summary>
    DropBell,

    /// <summary>
    /// Not a creature: a bell that a boss throws up, which bounces along the floor. Only the scene host's game runs
    /// them now, and the copy flies by itself with the same gravity (OwnMotionComponent).
    /// </summary>
    AttackBell,

    /// <summary>
    /// Not a creature: a pin that a boss fires across its arena, placed, turned and timed at random by the room and
    /// aimed at the player the boss is after. Only the scene host's game runs them now, and the copy flies by itself
    /// until the wall stops it (OwnMotionComponent).
    /// </summary>
    WeaverPin,

    /// <summary>
    /// Not a creature: a pin lying about the arena of the boss that fires <see cref="WeaverPin"/>s. The boss pulls one
    /// up for each pin it fires, and one is left where a fired pin lands, stuck there or falling. Which one is pulled,
    /// how fast it rises and whether it sticks were rolled by each game, and with the fired pins run by the scene host
    /// alone the other game's lay where they were while pins came out of nowhere. Only the scene host's game runs them
    /// now, and the copy rises, falls and bounces by itself (OwnMotionComponent).
    /// </summary>
    WeaverLoosePin
}
